# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#trigger:
#- main
schedules:
- cron: "0 21 * * *" # 9 PM UTC (0 minutes, 21 hours, every day)
  displayName: Daily 9:00 PM UTC
  branches:
    include:
    - main # Or your branch name
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'

- script: npm ci
  displayName: Install dependencies
  
- script: npx playwright install --with-deps
  displayName: Install Playwright Browsers

- script: npx playwright test --project=$(browser) --grep=$(tag)
  displayName: Run Playwright tests

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'playwright HTML report'
    publishLocation: 'pipeline'
  condition: always()   

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/PlaywrightJunitReporter.xml'
    testRunTitle: 'Junit Repoter'
  condition: always()